### ISSUE TITLE
Question: Clean way to call Texter when User phone number is not a required field?

### ISSUE THREAD

**Issue by kulte** [visualitypl/textris#31]
Perhaps this is a nit-pick, but currently we always have to do something like:

```ruby
UserTexter.welcome(user).deliver_later if user.phone?
```

Since the call to `#welcome` will fail without an E.164 compliant phone number, we cannot handle this at the job level. Also, returning `nil` from `#welcome` such that we now call:

```ruby
UserTexter.welcome(user)&.deliver_later
```

doesn't seem like much of an improvement. I'm wondering if this is consistent behavior in terms of the API for ActionMailer, and we just don't have to deal with this case because `email` is a field that does have a not-null constraint. **What is the way that you would imagine handling calling Texter methods in an app where phone is allowed to be null?**

**Comment by philnash** [comment]
I personally see no problem with you needing to guard against calling a method that will fail without a phone number. You wouldn't expect ActionMailer to send an email for an object without an email address, nor would you ask it to, so there should be no difference in Textris.

I'd also argue that `UserTexter.welcome(user)&.deliver_later` is just obscuring your intention.

Perhaps to make it even clearer, you should tell the job the arguments it needs rather than passing it an object to extract arguments from. The most obvious intention comes from something like:

```
UserTexter.welcome(user.email).deliver_later if user.phone?
```

Then your `UserTexter` just needs to receive an email address as an argument. Just an idea.

**Comment by Marahin** [comment]
There hasn't been any comments since, so I assume this issue is resolved. Thanks @philnash!
