### ISSUE TITLE
Queue name doesn't change

### ISSUE THREAD

**Issue by favour121** [visualitypl/textris#6]
The API for changing queue name doesn't work:

AccountTexter.welcome(user).deliver_later(queue: :sms_notifications)

**Comment by CollinGraves** [comment]
Assuming you're using Sidekiq as your queueing backend: did you declare the queue in your Sidekiq config file?

**Comment by karolsluszniak** [comment]
There was an issue in Textris with passing options to ActiveJob. For some reason, method for setting job options described in the [official guide](http://edgeguides.rubyonrails.org/active_job_basics.html#queues) didn't work so options like `queue` or `wait` were ignored.

I fixed it in b035fc0 and the fix is included in version `0.4.1`.
